-- V1: Create the existing RESPONSES and CONVERSATIONS tables
-- (as they exist in genai-data-plane before V2 migration)
-- This represents the pre-migration baseline schema.

------------------------------------------------------------
-- 1. RESPONSES
------------------------------------------------------------
CREATE TABLE RESPONSES (
    RESPONSE_ID              VARCHAR2(255)              NOT NULL,
    CONVERSATION_ID          VARCHAR2(255),
    PREVIOUS_RESPONSE_ID     VARCHAR2(255),
    INPUT_ITEMS              CLOB,
    RESPONSE_OBJECT          CLOB,
    MODEL                    VARCHAR2(255),
    CREATED_AT               TIMESTAMP WITH TIME ZONE,
    CONVERSATION_STORE_ID    VARCHAR2(255),
    GENERATIVE_AI_PROJECT_ID VARCHAR2(255),
    SUBJECT_ID               VARCHAR2(255),
    EXPIRES_AT               TIMESTAMP WITH TIME ZONE,
    CONSTRAINT PK_RESPONSES PRIMARY KEY (RESPONSE_ID)
);

CREATE INDEX IDX_RESPONSES_CONV_ID ON RESPONSES (CONVERSATION_ID);
CREATE INDEX IDX_RESPONSES_EXPIRES_AT ON RESPONSES (EXPIRES_AT);
CREATE INDEX IDX_RESPONSES_CREATED_AT ON RESPONSES (CREATED_AT);

------------------------------------------------------------
-- 2. CONVERSATIONS
------------------------------------------------------------
CREATE TABLE CONVERSATIONS (
    CONVERSATION_ID          VARCHAR2(255)              NOT NULL,
    CONVERSATION_STORE_ID    VARCHAR2(255),
    GENERATIVE_AI_PROJECT_ID VARCHAR2(255),
    CREATED_AT               TIMESTAMP WITH TIME ZONE   NOT NULL,
    METADATA                 CLOB,
    ITEMS                    CLOB,
    UPDATED_AT               TIMESTAMP WITH TIME ZONE,
    EXPIRES_AT               TIMESTAMP WITH TIME ZONE   NOT NULL,
    VERSION                  NUMBER DEFAULT 0           NOT NULL,
    SHORT_TERM_MEMORY        CLOB,
    SHORT_TERM_MEMORY_BYTES  NUMBER,
    CONSTRAINT PK_CONVERSATIONS_RECORD PRIMARY KEY (CONVERSATION_ID),
    CONSTRAINT CONV_VERSION_CK CHECK (VERSION >= 0)
);

CREATE INDEX IX_CONV_TTL_CLEANUP ON CONVERSATIONS (EXPIRES_AT);
CREATE INDEX IX_CONV_CONVERSATION_ID_CONVERSATION_STORE_ID ON CONVERSATIONS (CONVERSATION_ID, CONVERSATION_STORE_ID);
CREATE INDEX IX_CONV_CONVERSATION_STORE_ID ON CONVERSATIONS (CONVERSATION_STORE_ID);
CREATE INDEX IDX_CONVERSATIONS_PROJECT_ID ON CONVERSATIONS (GENERATIVE_AI_PROJECT_ID);
